<section class="main-content container">
    <h1 class="h1-xl"><?php echo lang('TermsOfService') ?></h1>
    <div class="general">
        <div class="interior">            
            <small><em>Last modified: September 28, 2014</em></small>

            <p>GlobalViP, Inc., a Delaware corporation (“GViP” or “we”), operates the website located at http://www.globalvipprojects.com, http://store.globalvipprojects.com, and such other subdomains of globalvipprojects.com as may from time to time be introduced (“the Site”), and provides services offered through the Site (collectively, “the Services”) directed at residents of the United States and residents of other countries accessing the Site, whether in the English language or in other languages, including Services offered free of charge (“Standard Services”) and additional services offered for a fee (“Premium Services”). The Services are hosted in the United States. This Terms of Service Agreement, as may be modified from time to time (“the Agreement”), constitutes legally binding terms and applies to your use of the Services. By accessing or using the Services, you agree to be bound by this Agreement, whether you are a Visitor (which means that you simply browse the Services, including, without limitation, through a mobile or other wireless device, or otherwise use the Services without being registered) or you are a Member (which means that you have registered with the Site). The term User refers to a Visitor or a Member. You are authorized to use the Services (regardless of whether your access or use is intended) only if you agree to abide by all applicable laws, rules and regulations (“Applicable Law”) and the terms of this Agreement. In addition, in consideration for becoming a Member and/or making use of the Services, you must indicate your acceptance of this Agreement during the registration process. Your use of, or participation in, certain Services may be subject to additional terms, and such terms will be either listed in this Agreement or will be presented to you for your acceptance when you sign up to use such Services.</p>
            <p>We reserve the right to modify this Agreement at any time and from time to time, and each such modification shall be effective upon posting on the Services. All material modifications will apply prospectively only. Your continued use of the Services following any such modification constitutes your agreement to be bound by and your acceptance of the Agreement as so modified. It is therefore important that you review this Agreement regularly. If you do not agree to be bound by this Agreement and to abide by all Applicable Law, you must discontinue use of the Services immediately.</p>

            <h2>1. Eligibility</h2>
            <p>Use of the Services and registration to be a Member for the Services (Membership) is void where prohibited. By using the Services, you represent and warrant that (a) all registration information you submit is truthful and accurate; (b) you will maintain the accuracy of such information; (c) you are 13 years of age or older; and (d) your use of the Services does not violate any Applicable Law.</p>

            <h2>2. Term</h2>
            <p>This Agreement, and any posted revision to this Agreement, shall remain in full force and effect while you use the Services or are a Member. You may terminate your Membership at any time, for any reason. In order to do so, please contact us by email at <a href="mailto:info@globalvipprojects.com">info@globalvipprojects.com</a> requesting termination. By choosing to terminate your Membership, you acknowledge and expressly agree that some or all of the information contained within your Profile, Projects and any such other content or data as may have arisen through your use of the Service may be irrevocably deleted. GViP may terminate your Membership at any time, for any or no reason, with or without prior notice or explanation, and without liability. Furthermore, we reserve the right, in our sole discretion, to reject, refuse to post or remove any posting (including, without limitation, private messages between you and other Users), or to deny, restrict, suspend, or terminate your access to all or any part of the Services at any time, for any or no reason, with or without prior notice or explanation, and without liability. Even after Membership is terminated, this Agreement will remain in effect, including, without limitation, Sections 8-20.</p>

            <h2>3. Registration and Fees</h2>
            <p>The Standard Services are made available to you free of charge. In order to access the Standard Services, you are required to fill out the registration form by providing all required information, and choose a password that you can modify at any time. In order to use the Premium Services, you must register for the Standard Services and pay a subscription fee as set forth on the applicable subscription page. A processing period of up to 72 hours may be required before you benefit from access to the Premium Services, and access will only be granted provided that the payment is valid. If you choose to terminate your subscription, you will not be entitled to any refund of fees paid for that subscription period.</p>

            <h2>4. Standard Services</h2>
            <p>GViP enables Members to create a profile (“Profile”) and publish it online. The project section (“Project”) allows Members to integrate and publish information regarding projects with which they are affiliated. Profiles are accessible on the Site through a directory and can also be found with the help of a search engine. Further details regarding other persons’ access to your Profile and Projects are set forth in our <a href="/privacy">Privacy Policy</a>.</p>

            <h2>5. Password</h2>
            <p>When you sign up to become a Member, you may also be asked to choose a password. You are entirely responsible for maintaining the confidentiality of your password. You agree not to use the account, username, email address or password of another Member at any time or to disclose your password to any third party. You agree to notify GViP immediately [mailto:info@globalvipprojects.com] if you suspect any unauthorized use of your account or access to your password. You are solely responsible for any and all use of your account.</p>

            <h2 >6. Use by Members</h2>
            <p>The Services are for the personal and professional use of Members and may only be used for direct commercial purposes if specifically endorsed or authorized by GViP. We reserve the right to remove commercial content at our sole discretion. Illegal and/or unauthorized use of the Services, including, without limitation, collecting User information by electronic or other means for the purpose of sending unsolicited email or unauthorized framing of or linking to the Services, is prohibited. Commercial advertisements, affiliate links, and other forms of unauthorized data collection or solicitation may be removed without notice or explanation and may result in termination of Membership privileges. We reserve the right to take appropriate legal action for any illegal or unauthorized use of the Services.</p>

            <h2>7. Proprietary Rights in Content</h2>
            <p>By posting any Content on, through or in connection with the Services, you hereby grant to GViP a license to use, modify, delete from, add to, publicly perform, publicly display, reproduce, and distribute such Content on, through or in connection with the Services, including, without limitation, distributing part or all of the Services and any Content included therein, in any media formats and through any media channels. After you remove your Content from the Services we will cease distribution as soon as practicable, and at such time as distribution ceases, the license will terminate. The license you grant to GViP is non-exclusive, fully paid and royalty-free, sublicensable, and worldwide. You represent and warrant that: (i) you own the Content or otherwise have the right to grant the license set forth in this Section 9, and (ii) the posting of your Content on, through or in connection with the Services does not violate the privacy rights, publicity rights, copyrights, contract rights or any other rights of any person or entity. You agree to pay for all royalties, fees, and any other monies owing any person or entity by reason of the use of any Content posted by you on or through the Services. The Services also contain Content of GViP ("GViP Content"). GViP Content is protected by copyright, trademark, patent, trade secret and other laws, and we own and retain all rights in the GViP Content and the Services. GViP hereby grants you a limited, revocable, nonsublicensable license to reproduce and display the GViP Content (excluding any software code) solely for your personal use in connection with viewing the Site and using the Services.</p>

            <h2>8. Content Posted</h2>
            <p>Please choose carefully the information that you post on, through or in connection with the Services and that you provide to other Users. You may not post any form of Prohibited Content, as outlined in Section 9 below. Despite this prohibition, information, materials, products or services provided by other Members may, in whole or in part, be unauthorized, impermissible or otherwise violate this Agreement, and GViP assumes no responsibility or liability for this material. If you become aware of misuse of the Services by any person, please <a href="mailto:info@globalvipprojects.com">contact us</a> immediately. GViP may reject, refuse to post or delete any Content for any or no reason, including, but not limited to, Content that in our sole judgment violates this Agreement or which may be offensive, illegal or violate the rights of any person or entity, or harm or threaten the safety of any person or entity. We assume no responsibility for monitoring the Services for inappropriate Content or conduct. If at any time we choose, in our sole discretion, to monitor the Services, we nonetheless assume no responsibility for the Content, no obligation to modify or remove any inappropriate Content, and no responsibility for the conduct of the User submitting any such Content. You are solely responsible for the Content that you post on, through or in connection with any of the Services, and any material or information that you transmit to other Members and for your interactions with other Users.</p>

            <h2>9. Content/Activity Prohibited</h2>
            <p>The following are examples of the kind of Content that is illegal or prohibited to post on, through or in connection with the Services. We reserve the right to investigate and take appropriate legal action against anyone who, at our sole discretion, violates this provision. Prohibited Content includes, but is not limited to, Content that, in our sole discretion: (a) is patently offensive or promotes or otherwise incites racism, bigotry, hatred or physical harm of any kind against any group or individual; (b) harasses or advocates harassment of another person; (c) exploits people in a sexual or violent manner; (d) contains nudity, violence, or offensive subject matter or contains a link to an adult website; (e) solicits or is designed to solicit personal information from anyone under 18; (f) publicly posts information that poses or creates a privacy or security risk to any person; (g) constitutes or promotes information that you know is false or misleading or promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libelous; (h) constitutes or promotes an illegal or unauthorized copy of another person’s copyrighted work; (i) involves the transmission of junk mail, chain letters, or unsolicited mass mailing, instant messaging, or spamming; (j) contains restricted or password only access pages or hidden pages or images; (k) furthers or promotes any criminal activity or enterprise or provides instructional information about illegal activities; (l) solicits or is designed to solicit passwords or personal identifying information for commercial or unlawful purposes from other Users; (m) involves commercial activities and/or sales without prior written consent from GViP such as contests, sweepstakes, barter, advertising, or pyramid schemes; (n) includes a photograph or video of another person that you have posted without that person’s consent; or (o) violates or attempts to violate the privacy rights, publicity rights, copyrights, trademark rights, contract rights or any other rights of any person.</p>

            <h2>10. Protecting Copyrights and Other Intellectual Property</h2>
            <p>GViP respects the intellectual property of others, and requires that our users do the same. You may not upload, embed, post, email, transmit or otherwise make available any material that infringes any copyright, patent, trademark, trade secret or other proprietary rights of any person or entity. It is GViP’s policy to terminate, in appropriate circumstances, the membership of repeat infringers.</p>
            <p>If you believe your work has been copied and posted on or through the Services in a way that constitutes copyright infringement, please send our Copyright Agent a notification of claimed infringement with all of the following information: (a) identification of the copyrighted work claimed to have been infringed; (b) identification of the claimed infringing material and information reasonably sufficient to permit us to locate the material on the Services (providing the URL(s) of the claimed infringing material satisfies this requirement); (c) information reasonably sufficient to permit us to contact you, such as an address, telephone number, and, if available, an email address; (d) a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; (e) a statement by you, made under penalty of perjury, that the above information in your notification is accurate and that you are the copyright owner or are authorized to act on the copyright owner’s behalf; and (f) your physical or electronic signature. Our Copyright Agent for notification of claimed infringement can be reached as follows: Copyright Agent, GViP, Inc., 1827 Jefferson Pl NW, Washington, DC, USA, Fax: +1 202.776.0994; Phone: +1 202.776.0990; Attn: Copyright Agent. Our Copyright Agent can also be reached electronically at <a href="mailto:info@globalvipprojects.com">info@globalvipprojects.com.</a></p>

            <h2>11. Member Disputes</h2>
            <p>You are solely responsible for your interactions with other Users, third-party developers or any other parties with whom you interact through the Services. GViP reserves the right, but has no obligation, to become involved in any way with these disputes.</p>

            <h2>12. Privacy</h2>
            <p>Use of the Services is also governed by our <a href="/privacy">Privacy Policy</a>, which is incorporated into this Agreement by this reference.</p>

            <h2>13. Disclaimers</h2>
            <p>GViP is not responsible for and makes no warranties, express or implied, as to the User Content or the accuracy and reliability of the User Content posted through or in connection with the Services, by Users of the Services, and such User Content does not necessarily reflect the opinions or policies of GViP. In addition, GViP is not responsible for any damage, injury or loss caused by Users of the Services or by any of the equipment or programming associated with or utilized in the Services. Web pages or profiles created and posted by Members on, through or in connection with the Services may contain links to other websites or services. GViP is not responsible for the Content, accuracy or opinions expressed on such websites and services, and such websites and services are not necessarily investigated, monitored or checked for accuracy or completeness by GViP. Inclusion of any linked website or service on the Services does not imply approval or endorsement of the linked website or service by GViP. When you access these third-party sites and services, you do so at your own risk. GViP takes no responsibility for third-party advertisements that are posted on, through or in connection with the Services, nor does it take any responsibility for the goods or services provided by these third parties. GViP is not responsible for the conduct, whether online or offline, of any User of the Services. GViP assumes no responsibility for any error, omission, interruption, deletion, defect, delay in operation or transmission, communications line failure, theft or destruction or unauthorized access to, or alteration of, any User or Member communication. GViP is not responsible for any problems or technical malfunction of any telephone network or lines, computer online systems, servers or providers, computer equipment, software, failure of any email or players due to technical problems or traffic congestion on the Internet or on any of the Services or combination thereof, including, without limitation, any injury or damage to Users or to any person’s computer related to or resulting from participation or downloading materials in connection with the Services. Under no circumstances shall GViP be responsible for any loss or damage, including, without limitation, personal injury or death, resulting from use of the Services, attendance at any event, from any User Content posted on or through the Services, or from the conduct of any Users of the Services, whether online or offline. The Services are provided as is and as available and GViP expressly disclaims any warranty of fitness for a particular purpose or non-infringement. GViP cannot guarantee and does not promise any specific results from use of the Services.</p>

            <h2>14. Limitation on Liability</h2>
            <p>IN NO EVENT SHALL GVIP BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL OR PUNITIVE DAMAGES, INCLUDING, WITHOUT LIMITATION, LOST PROFIT DAMAGES ARISING FROM YOUR USE OF THE SERVICES, EVEN IF GVIP HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, GVIP’S LIABILITY TO YOU FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION, WILL AT ALL TIMES BE LIMITED TO THE AMOUNT PAID, IF ANY, BY YOU TO GVIP FOR THE SERVICES.</p>

            <h2>15. U.S. Export Controls</h2>
            <p>Software available in connection with the Services (the Software) is further subject to United States export controls. No Software may be downloaded from the Services or otherwise exported or re-exported in violation of U.S. export laws. Downloading or using the Software is at your sole risk.</p>

            <h2>16. Disputes</h2>
            <p>The Agreement shall be governed by, and construed in accordance with, the laws of the District of Columbia, without regard to its conflict of law provisions. You and GViP agree to submit to the exclusive jurisdiction of the District and federal courts located in Washington, DC, to resolve any dispute arising out of the Agreement or the Services. EACH OF THE PARTIES HEREBY KNOWINGLY, VOLUNTARILY AND INTENTIONALLY WAIVES ANY RIGHT IT MAY HAVE TO A TRIAL BY JURY IN RESPECT OF ANY LITIGATION (INCLUDING, BUT NOT LIMITED TO, ANY CLAIMS, COUNTERCLAIMS, CROSS-CLAIMS, OR THIRD PARTY CLAIMS) ARISING OUT OF, UNDER OR IN CONNECTION WITH THIS AGREEMENT. FURTHER, EACH PARTY HERETO CERTIFIES THAT NO REPRESENTATIVE OR AGENT OF EITHER PARTY HAS REPRESENTED, EXPRESSLY OR OTHERWISE, THAT SUCH PARTY WOULD NOT IN THE EVENT OF SUCH LITIGATION, SEEK TO ENFORCE THIS WAIVER OF RIGHT TO JURY TRIAL PROVISION. EACH OF THE PARTIES ACKNOWLEDGES THAT THIS SECTION IS A MATERIAL INDUCEMENT FOR THE OTHER PARTY ENTERING INTO THIS AGREEMENT.</p>

            <h2>17. Indemnity</h2>
            <p>You agree to indemnify and hold GViP, its subsidiaries, and affiliates, subcontractors and other partners, and their respective officers, directors, agents, partners, employees and volunteers, harmless from any loss, liability, claim, or demand, including, but not limited to, reasonable attorneys’ fees, made by any third party due to or arising out of your use of the Services in violation of this Agreement, arising from a breach of this Agreement or any breach of your representations and warranties set forth in this Agreement, or any Content that you post on, through or in connection with the Services.</p>

            <h2>18. Other</h2>
            <p>This Agreement is accepted upon your use of the Site or any of the Services and is further affirmed by you becoming a Member. Your agreement with GViP will always include this Agreement at a minimum. Your access and use of certain Services may require you to accept additional terms and conditions applicable to such certain Services, in addition to this Agreement. The failure of GViP to exercise or enforce any right or provision of this Agreement shall not operate as a waiver of such right or provision. The section titles in this Agreement are for convenience only and have no legal or contractual effect. This Agreement operates to the fullest extent permissible by law. If any provision of this Agreement is unlawful, void or unenforceable, that provision is deemed severable from this Agreement and does not affect the validity and enforceability of any remaining provisions.</p>
            <br>
            <p>To contact us regarding any questions about this Agreement, please write to <a href="mailto:info@globalvipprojects.com">info@globalvipprojects.com</a>.</p>
        </div>
    </div>
    <br>
    <a href="/" class="btn ctr lt-blue">Back to the home page</a>
</section>